# Generated by Django 3.0.2 on 2020-01-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0003_auto_20200128_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image_path',
            field=models.TextField(max_length=65535),
        ),
    ]
