# Generated by Django 3.0.2 on 2020-01-29 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0004_auto_20200129_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='page_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='url',
            field=models.TextField(default='', max_length=65535),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='url_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
